Feature/data processing unit implementation
IIS-ZPI/ZPI2023_zaoczni_BogoSort pull request #38
Opened 2024-01-21 13:43 UTC by jacekdebski

2024-01-24 16:39 UTC, mikoogla commented on src/components/data_processing_unit/data_processing_unit.py
> +            "median": median,
median is imported from statistics and also median: float declaration there is.

2024-01-24 16:43 UTC, mikoogla requested changes
name fix to do

2024-01-26 15:08 UTC, jacekdebski commented on src/components/data_processing_unit/data_processing_unit.py
> +            "median": median,
imported all functions from statistics module to easier differentiate local variables

2024-01-27 12:22 UTC, rfilipczak submitted a review, later dismissed
lgtm

2024-01-27 12:39 UTC, rfilipczak reviewed
nvm

2024-01-28 12:41 UTC, rfilipczak approved these changes

2024-01-28 13:01 UTC, mikoogla approved these changes

2024-01-28 13:02 UTC, merged